### ISSUE TITLE
Running toxcodan issues

### ISSUE THREAD

**Issue by jjyotikataria** [pedronachtigall/Venomancer#4]
I have installed these pre-requisites and they seem to be working fine. But however in the outputs, I am getting some files with 0 size.

1. Is there something wrong?

Requirements:
export PATH=$PATH:/home/jyoti.k/Snake/ncbi-blast-2.11.0+/bin/
export PATH=$PATH:/home/jyoti.k/Snake/signalp-4.1/
export PATH=$PATH:/home/jyoti.k/Snake/ToxCodAn/bin/
export PATH=$PATH:/home/jyoti.k/Snake/CodAn/bin/
export PATH=$PATH:/home/jyoti.k/Snake/biopython-1.78

Command ran: toxcodan.py -t Mfulv.fasta -m models/ -o TEST -c 20

Output folder name : TEST

-bash-4.2$ ls -lrth TEST/
total 2.1M
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 19:58 blastDB
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_ACHE_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_HYAL_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_MYO_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_PDE_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_VEGF_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_3FTx_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_CTL_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_KUN_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_NUC_out
drwxr-xr-x 2 jyoti.k ngsmdgrp 4.0K May 12 20:01 TOXIN_PLA2_out
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:02 toxcodan_Toxins_annotation.gtf
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:02 toxcodan_Toxins_contigs.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp 284K May 12 20:02 toxcodan_PutativeToxins_contigs.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp 1.5M May 12 20:02 toxcodan_NonToxins_contigs.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp  95K May 12 20:07 toxcodan_PutativeToxins_contigs_SPfiltered.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:07 toxcodan_Toxins_cds.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:07 toxcodan_PutativeToxins_cds.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp  59K May 12 20:07 toxcodan_PutativeToxins_cds_SPfiltered.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:07 toxcodan_Toxins_pep.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp  22K May 12 20:07 toxcodan_PutativeToxins_pep_SPfiltered.fasta
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:07 RemoveRedundancy.log
-rw-r--r-- 1 jyoti.k ngsmdgrp    0 May 12 20:07 toxcodan_Toxins_cds_RedundancyFiltered.fasta

2. I am getting these prompts while running but they don't seem to be there in the tutorial log file. Could you help me with the reason behind this too?

rm: cannot remove ‘TEST/TOXIN_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_ACHE_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_HYAL_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_MYO_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_PDE_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_VEGF_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_3FTx_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_CTL_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_KUN_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_NUC_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory
rm: cannot remove ‘TEST/TOXIN_PLA2_out/minus.fa.*’: No such file or directory
rm: cannot remove ‘TEST/PreFilter_WC.fa.index*’: No such file or directory

**Comment by pedronachtigall** [comment]
Hi @jjyotikataria,

I am fine, thanks for asking. I also hope that you and all your family are doing well despite covid still surrounding us all.

As I can see, CodAn (https://github.com/pedronachtigall/CodAn) is not performing its CDS prediction (the issue "2" is causing the issue "1" pointed by you).
You need to ensure that CodAn is properly working to run ToxCodAn.
Check this issue in CodAn issue's section: https://github.com/pedronachtigall/CodAn/issues/8
    - it may help you.
Try to run CodAn tutorial to ensure it is working properly: https://github.com/pedronachtigall/CodAn/tree/master/tutorial

Did you install each requirement of ToxCodAn separately or installed the conda environment?
 - If you used conda environment, you may also need to run `conda install -c bioconda perl-bioperl-core` (it depended on each system/server it is being installed)

Let me know if it helped you or if you are still having trouble setting up ToxCodAn.

Best regards,
Pedro

**Comment by jjyotikataria** [comment]
@pedronachtigall Thank you for your quick reply Pedro. My server configuration is as follows and it didn't work for CentOS for me. It worked on ubuntu though.

-bash-4.2$ hostnamectl
   Static hostname: server1
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 8f19f812270346ca841a060ba094d4ab
           Boot ID: 96849c8984a94db5a6f1697ec9d86b9b
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.5.1.el7.x86_64
      Architecture: x86-64
